name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build
      run: dotnet build -c Release
    - name: Package
      run: dotnet pack /p:Version=2.$GITHUB_RUN_NUMBER.$GITHUB_RUN_ID -c Release
    - name: Publish
      run: dotnet nuget push Walle.Components.MongoDB.2.$GITHUB_RUN_NUMBER.$GITHUB_RUN_ID.nupkg --api-key ${{secrets.NUGET_MISAYA_KEY}} --source https://api.nuget.org/v3/index.json
