name: dotNetStandard

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build
      run: dotnet build -c Release
    - name: Package
      run: dotnet pack /p:Version=2.0.$GITHUB_RUN_NUMBER -c Release -o ./
    - name: Publish-microsoft-nuget
      run: dotnet nuget push Walle.Components.MongoDB.2.0.$GITHUB_RUN_NUMBER.nupkg --api-key ${{secrets.NUGET_MISAYA_KEY}} --source https://api.nuget.org/v3/index.json
    - name: Publish-github-nuget
      run: dotnet nuget push Walle.Components.MongoDB.2.0.$GITHUB_RUN_NUMBER.nupkg --api-key ${{secrets.MISAYA_PAT}} --source https://nuget.pkg.github.com/OWNER/index.json
