name: dotNetStandard

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      VERSION: 2.0.$GITHUB_RUN_NUMBER.$GITHUB_RUN_ID
      NAME: Walle.Components.MongoDB
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: ECHO
      run: echo '${{env.NAME}}.${{env.VERSION}}'
    - name: Build
      run: dotnet build /p:Version=${{env.VERSION}} -c Release  
    - name: Package
      run: dotnet pack /p:Version=${{env.VERSION}} -c Release -o ./
    - name: Publish-microsoft-nuget
      run: dotnet nuget push ${{env.NAME}}.${{env.VERSION}}.nupkg --api-key ${{secrets.NUGET_MISAYA_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
    - name: Publish-github-nuget
      run: dotnet nuget push ${{env.NAME}}.${{env.VERSION}}.nupkg --api-key ${{secrets.MISAYA_PAT}} --source https://nuget.pkg.github.com/OWNER/index.json
